extends Control
var list:VBoxContainer
var summary:VBoxContainer
var defs={"militia":["Militia","Cheap line infantry. Reliable bodies for 1 Command."],"archer":["Archer","Ranged support. Excellent behind a moving frontline."],"wolf":["War Wolf","Fast skirmisher that tears into isolated enemies."],"mage":["Mage","Expensive area damage. Requires Arcane Lab."]}
func _ready()->void:_build();GameState.changed.connect(refresh);refresh()
func _exit_tree()->void:
	if GameState.changed.is_connected(refresh):GameState.changed.disconnect(refresh)
func _build()->void:
	var margin=MarginContainer.new();margin.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT);margin.add_theme_constant_override("margin_left",24);margin.add_theme_constant_override("margin_right",24);margin.add_theme_constant_override("margin_top",18);margin.add_theme_constant_override("margin_bottom",18);add_child(margin);var root=HBoxContainer.new();root.add_theme_constant_override("separation",16);margin.add_child(root);var left=VBoxContainer.new();left.size_flags_horizontal=Control.SIZE_EXPAND_FILL;root.add_child(left);left.add_child(UIFactory.title("Warband & Command",28));left.add_child(UIFactory.label("Every unit competes for Command capacity. Quality and quantity pull against the same budget.",13,Color("#9ca8c5")));left.add_child(UIFactory.hsep());list=VBoxContainer.new();list.add_theme_constant_override("separation",10);left.add_child(list);var side=PanelContainer.new();side.custom_minimum_size.x=330;side.add_theme_stylebox_override("panel",UIFactory.panel(Color("#151b2a"),12,Color("#35415d")));root.add_child(side);summary=VBoxContainer.new();side.add_child(summary)
func refresh()->void:
	if not is_inside_tree():return
	UIFactory.clear_children(list)
	for unit in defs:
		var p=PanelContainer.new();p.add_theme_stylebox_override("panel",UIFactory.panel(Color("#181f31"),10,Color("#35415f")));var v=VBoxContainer.new();p.add_child(v);var h=HBoxContainer.new();v.add_child(h);h.add_child(UIFactory.label("%s · Rank %d"%[defs[unit][0],GameState.unit_levels[unit]],18,Color("#eadfbf")));h.add_child(UIFactory.spacer());h.add_child(UIFactory.label("×%d   Command %d ea."%[GameState.army[unit],GameState.unit_command_cost(unit)],13));v.add_child(UIFactory.label(defs[unit][1],12,Color("#9ca8c5")));var actions=HBoxContainer.new();v.add_child(actions);actions.add_child(UIFactory.button("Recruit",func(u=unit):GameState.recruit(u),Color("#33465b")));actions.add_child(UIFactory.label(UIFactory.cost_text(GameState.recruitment_cost(unit)),11,Color("#a8b4ce")));actions.add_child(UIFactory.spacer());var train=UIFactory.button("Train Rank",func(u=unit):GameState.upgrade_unit(u),Color("#4b3d57"));train.custom_minimum_size.x=105;actions.add_child(train);list.add_child(p)
	UIFactory.clear_children(summary);summary.add_child(UIFactory.title("Command",23));summary.add_child(UIFactory.label("%d / %d used"%[GameState.command_used(),GameState.command_capacity()],22,Color("#f0dfae")));summary.add_child(UIFactory.label("Army Power  %d"%GameState.army_power(),15,Color("#a8d2aa")));summary.add_child(UIFactory.hsep());summary.add_child(UIFactory.label("Capacity grows from:",14));summary.add_child(UIFactory.label("• Warden level\n• Leadership research\n• Town Hall\n• future traits, artifacts & doctrines",12,Color("#9ca8c5")));summary.add_child(UIFactory.hsep());summary.add_child(UIFactory.label("Doctrine Preview",16,Color("#f0dfae")));summary.add_child(UIFactory.label("Future branches: Swarm, Vanguard, Arcane Host, Beastmaster, Cavalry and more.",12,Color("#9ca8c5")))
